apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bb-app
  template:
    metadata:
      labels:
        app: bb-app
    spec:
      containers:
      - name: bb-app
        image: bb-app-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000